package optimizer

// ParseTree data structure for the parsed input code
//type ParseTree struct {
//	Children *list.List
//	Value    interface{}
//}

// ParseTree represents a parse tree generated by the parser.
type ParseTree interface {
	Children() []ParseTree
}
